dbt_demo:
  target: dev
  outputs:
    dev:
      type: duckdb
      threads: 2
      extensions:
        - httpfs
        - parquet
      #settings:
      #  s3_region: us-east-1
      #  s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
      #  s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
    prod:
      type: duckdb
      threads: 2
      path: "md:my_db?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      extensions:
        - httpfs
        - parquet
